replacements = {
    'uttar pradesh': 'Uttar Pradesh',
    'up': 'Uttar Pradesh',
    'uttarpradesh': 'Uttar Pradesh',
    'madhya pradesh': 'Madhya Pradesh',
    'mp': 'Madhya Pradesh',
    'maharashtra': 'Maharashtra',
    'mahrashtra': 'Maharashtra',
    'haryana': 'Haryana',
    'hariyana': 'Haryana',
    'odisha': 'Odisha',
    'west bengal': 'West Bengal',
    'chhattisgarh': 'Chhattisgarh',
    'karnataka': 'Karnataka',
    'delhi': 'Delhi',
    'delhi ncr': 'Delhi',
    'rajasthan': 'Rajasthan',
    'rajisthan': 'Rajasthan',
    'tamil nadu': 'Tamil Nadu', 
    'gujrat': 'Gujarat',
    'maharastra': 'Maharashtra'
}

indian_states_ut = [
        'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Lakshadweep', 'Puducherry'
    ]

category_mapping = {
    'Computer Science': 'Computer Science',
    'CSE': 'Computer Science',
    'B.tech': 'Engineering',
    'BTech': 'Engineering',
    'B.Tech.': 'Engineering',
    'B.Tech': 'Engineering',
    'BTech-CSE': 'Computer Science',
    'Engeneering': 'Engineering',
    'Teacher': 'Others',
    'KIIT BHUBANESWAR': 'Computer Science',
    'BTECH - CSE': 'Computer Science',
    'React native, Machine learning': 'Computer Science',
    'Computer Science Engineering': 'Computer Science',
    'KIIT': 'Others',
    'BTECH IN CSE': 'Computer Science',
    'B. Tech.': 'Engineering',
    "Bachelor's in design": 'Design',
    'School student': 'Others',
    'BFA': 'Design',
    'Political Science Honours': 'Others',
    'Biotechnology': 'Others',
    'CSE': 'Computer Science',
    'BA LLB': 'Others',
    'Animation and interior design': 'Design',
    'B tech, electrical engineering': 'Engineering',
    'Bcom': 'Commerce',
    'Chartered Accountancy': 'Others',
    'Mechanical Engineering': 'Engineering',
    'Information Technology': 'Engineering',
    'Engineering': 'Engineering',
    'B.Com hons (marketing) with Liberal Arts': 'Commerce',
    'BAMS': 'Medical',
    'B.Tech. in Artificial Intelligence and Data Science': 'Engineering',
    'BA Hons. - Psychology': 'Psychology',
    'BCom Honors': 'Commerce',
    'BA Psychology Honors': 'Psychology',
    'B.tech CS (IOT - CYBERSECURITY)': 'Computer Science',
    'BCA': 'Others',
    'Btech in Computer Science Engineering': 'Computer Science',
    'Graphic Design': 'Design',
    'Psychology': 'Psychology',
    'Architecture': 'Design',
    'Studied architecture': 'Design',
    'BTech CSE': 'Computer Science',
    'Preparing For Civil Services !!': 'Others',
    'Masters in economics': 'Others',
    'B.TECH': 'Engineering',
    'btech cse': 'Computer Science',
    'Btech(CSE)': 'Computer Science',
    'Finance in Mba': 'MBA',
    'B.com hons.': 'Commerce',
    'B com': 'Commerce',
    'BTECH': 'Engineering',
    'No': 'Others',
    'Commerce': 'Commerce',
    'Bsc Computer Science': 'Computer Science',
    'BSc. Applied Psychology': 'Psychology',
    'Bdes': 'Design',
    'Bachelor’s of Applied IT': 'Others',
    'Books': 'Others',
    'Design': 'Design',
    '-': 'Others',
    'Neet': 'Medical',  
    'Fashion design': 'Fashion',
    'B.Des': 'Design',
    'Bachelors in Dental Surgery': 'Medical',  
    'Math': 'Others',
    'B. Tech': 'Engineering',
    'Bachelors of Technology in Computer Science': 'Computer Science',
    'IITBOMBAY': 'Engineering',  
    'Bsc': 'BSc',  
    'BTech Aerospace Engineering': 'Engineering',
    'btech aerospace': 'Engineering',
    'MBA': 'MBA',
    'Film studies': 'Others',
    'B.tech aerospace engineering': 'Engineering',
    'BTech Aerospace': 'Engineering',
    'Aerospace Engineering': 'Engineering',
    'MBA - Operations and SCM': 'MBA',
    'B-tech': 'Engineering',
    'Mathematics and computing': 'Others',
    'In job': 'Others',
    'B.Tech CSE': 'Computer Science',
    'WINDCHILL+': 'Others',
    'computer': 'Others',
    'Bsc IT': 'BSc',
    'Bcom accounting and finance': 'Commerce',
    'Bsc nursing': 'Medical',
    'fashion': 'Fashion',
    'Computer science': 'Computer Science',
    'Computer Science and Engineering': 'Computer Science',
    'Btech': 'Engineering',
    'B tech': 'Engineering',
    'B. Tech': 'Engineering',
    'Btech cse': 'Computer Science',
    'B.Tech CSE': 'Computer Science',
    'Computer Science and Communication Engineering': 'Computer Science',
    'BSc Computer Science': 'Computer Science',
    'Btech CSE': 'Computer Science',
    'Btech in cse': 'Computer Science',
    'B tech aerospace': 'Engineering',
    'B.tech aerospace engineering': 'Engineering',
    'BTech Aerospace': 'Engineering',
    'Aerospace Engineering': 'Engineering',
    'Btech Aerospace': 'Engineering',
    'B. Tech in Computer Science and Engineering': 'Computer Science',
    'B tech, electrical engineering': 'Engineering',
    'Bcom accounting and finance': 'Commerce',
    'Bcom hons.': 'Commerce',
    'B com': 'Commerce',
    'B.Com hons (marketing) with Liberal Arts': 'Commerce',
    'MBA - Operations and SCM': 'MBA',
    'Masters in economics': 'Others',
    'Fashion design': 'Fashion',
    'Studied architecture': 'Design',
    'Architecture': 'Design',
    'Graphic Design': 'Design',
    'Animation and interior design': 'Design',
    'Bachelor’s of Applied IT': 'Others',
    'Biotechnology': 'Others',
    'BAMS': 'Medical',
    'Bachelors in Dental Surgery': 'Medical',
    'BSc. Applied Psychology': 'Psychology',
    'BA Hons. - Psychology': 'Psychology',
    'Computer': 'Others',
    'Math': 'Others',
    'No': 'Others',
    'B. Tech CSE': 'Computer Science',
    'Computer science engineering': 'Computer Science',
    'BTech in CSE': 'Computer Science',
    "Bachelor's of design": 'Design',
    'BTech(CSE)': 'Computer Science',
    'International relations with defence and strategic Studies Research': 'Others',
    'B Tech CSE': 'Computer Science',
    'BA': 'Others',
    'B.Tech. in Computer Science and Engineering': 'Computer Science',
    'B.Tech computer science': 'Computer Science',
    'Senior High School': 'Others',
    'BBA': 'Others',
    'B.tech,CSE': 'Computer Science',
    'B.tech Aerospace Engineering': 'Engineering',
    'Bachelors in Design ( Animation, vfx and Illustration)': 'Design',
    'Computer science and engineering' : 'Computer Science', 'BTech in cse':'Computer Science'
}

input_mapping = {
    'SignificantDecline' : 'Significant decline',
    'SlightDecline': 'Slight decline',
    'NoChange' : 'No change',
    'IncreasedAppetite' : 'Increased appetite',
    'DecreasedAppetite' :'Decreased appetite' ,
    'WeightGain':'Weight gain',
    'WeightLoss' :'Weight loss',
    'Bachelor1' :'Bachelor 1st Year',
    'Bachelor2' :'Bachelor 2nd Year',
    'Bachelor3' :'Bachelor 3rd Year',
    'Bachelor4' :'Bachelor 4th Year',
} 